### ISSUE TITLE
Feature Proposal: Custom Link to Ghidra Release

### ISSUE THREAD

**Issue by fmagin** [er28-0652/setup-ghidra#7]
First off, thanks for writing this action, this makes building extensions really easy and I have been using it with various of my projects.
Currently I am working on something that (until some changes are upstreamed one day) requires a fork of Ghidra against which I am building an extension and I'd like to automatically build this extension in a GitHub Action.

The feature that would greatly help with this is the option to directly pass the link the the zip file like `https://ghidra-sre.org/ghidra_9.2.2_PUBLIC_20201229.zip` or in my case the link to the prebuilt fork (probably as a released asset in another public GitHub repo. 

To me it looks like this should be fairly easy by adding an extra parameter to `installGhidra` and some logic to download the file from this URL instead of `GHIDRA_BASE_URL + ghidraVersionInfo.archive`.
I am not familiar with writing GitHub actions myself yet, so I can't judge if I am missing some subtleties that makes this harder, but if it is really as simple as that, I can submit a PR for this.

**Comment by er28-0652** [comment]
thank you for your PR. I've merged it. If you have any further issue, please feel free to let me know.
